### PR TITLE
Add Guide Page and Header links

### PR DESCRIPTION
**Pull request by kyleThomas123**
Header links
Add a guide place holder

### CODE REVIEW

**Comment by kyleThomas123** [comment]
I like 'Submit Sales' instead of 'add points' @Sk1nnyB could you change it in your PR

**Comment by Sk1nnyB** [comment]
Lgtm!

**Comment by Sk1nnyB** [comment]
Lgtm attempt 2!

**Review by Sk1nnyB — APPROVED** [review]
Lgtm #3!

**Pull request merged**
